language: python
python:
- 2.6
- 2.7
- 3.2
- 3.3
- 3.4
- pypy
- pypy3
install:
- pip install flake8 pytest
- pip install -e .
script:
- | # flake8
  if [[ $(python --version 2>&1) == "Python 2."* ]]
  then
    EXCLUDE=profiling/remote/asyncio.py
  fi
  flake8 profilng test setup.py --show-source --ignore=E301 --exclude=$EXCLUDE
- | # pytest
  py.test -v
